-- MySQL Script generated by MySQL Workbench
-- Sat 26 Aug 2017 02:42:58 PM EAT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema survey
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema survey
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `survey` DEFAULT CHARACTER SET utf8 ;
USE `survey` ;

-- -----------------------------------------------------
-- Table `survey`.`tbl_role`
-- -----------------------------------------------------
--DROP TABLE IF EXISTS `survey`.`tbl_role` ;

CREATE TABLE IF NOT EXISTS `survey`.`tbl_role` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(100) NULL,
  `last_update` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `name_UNIQUE` ON `survey`.`tbl_role` (`name` ASC);


-- -----------------------------------------------------
-- Table `survey`.`tbl_user`
-- -----------------------------------------------------
--DROP TABLE IF EXISTS `survey`.`tbl_user` ;

CREATE TABLE IF NOT EXISTS `survey`.`tbl_user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `email` VARCHAR(100) NULL,
  `role_id` INT NOT NULL,
  `enabled` INT NULL DEFAULT 0,
  `status` VARCHAR(45) NULL DEFAULT 'ACTIVE',
  `last_update` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_tbl_user_tbl_role1`
    FOREIGN KEY (`role_id`)
    REFERENCES `survey`.`tbl_role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_tbl_user_tbl_role1_idx` ON `survey`.`tbl_user` (`role_id` ASC);

CREATE UNIQUE INDEX `username_UNIQUE` ON `survey`.`tbl_user` (`username` ASC);


-- -----------------------------------------------------
-- Table `survey`.`tbl_project`
-- -----------------------------------------------------
--DROP TABLE IF EXISTS `survey`.`tbl_project` ;

CREATE TABLE IF NOT EXISTS `survey`.`tbl_project` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `status` VARCHAR(45) NULL DEFAULT 'ACTIVE',
  `last_update` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `survey`.`tbl_form_repository`
-- -----------------------------------------------------
--DROP TABLE IF EXISTS `survey`.`tbl_form_repository` ;

CREATE TABLE IF NOT EXISTS `survey`.`tbl_form_repository` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `description` VARCHAR(100) NULL,
  `filepath` VARCHAR(100) NULL,
  `project_id` INT NOT NULL,
  `status` VARCHAR(45) NULL DEFAULT 'ACTIVE',
  `last_update` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `version` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_tbl_form_repository_tbl_project1`
    FOREIGN KEY (`project_id`)
    REFERENCES `survey`.`tbl_project` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_tbl_form_repository_tbl_project1_idx` ON `survey`.`tbl_form_repository` (`project_id` ASC);


-- -----------------------------------------------------
-- Table `survey`.`tbl_form`
-- -----------------------------------------------------
--DROP TABLE IF EXISTS `survey`.`tbl_form` ;

CREATE TABLE IF NOT EXISTS `survey`.`tbl_form` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `repository_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `status` VARCHAR(45) NULL DEFAULT 'ACTIVE',
  `last_update` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `repos_version` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_tbl_form_tbl_form_repository1`
    FOREIGN KEY (`repository_id`)
    REFERENCES `survey`.`tbl_form_repository` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_form_tbl_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `survey`.`tbl_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_tbl_form_tbl_form_repository1_idx` ON `survey`.`tbl_form` (`repository_id` ASC);

CREATE INDEX `fk_tbl_form_tbl_user1_idx` ON `survey`.`tbl_form` (`user_id` ASC);


-- -----------------------------------------------------
-- Table `survey`.`tbl_form_data`
-- -----------------------------------------------------
--DROP TABLE IF EXISTS `survey`.`tbl_form_data` ;

CREATE TABLE IF NOT EXISTS `survey`.`tbl_form_data` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `metadata` VARCHAR(100) NULL,
  `rawvalue` VARCHAR(100) NULL,
  `form_id` INT NOT NULL,
  `datatype` VARCHAR(45) NULL,
  `last_update` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_tbl_form_data_tbl_form1`
    FOREIGN KEY (`form_id`)
    REFERENCES `survey`.`tbl_form` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_tbl_form_data_tbl_form1_idx` ON `survey`.`tbl_form_data` (`form_id` ASC);


-- -----------------------------------------------------
-- Table `survey`.`tbl_user_project`
-- -----------------------------------------------------
--DROP TABLE IF EXISTS `survey`.`tbl_user_project` ;

CREATE TABLE IF NOT EXISTS `survey`.`tbl_user_project` (
  `last_update` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `user_id` INT NOT NULL,
  `project_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `project_id`),
  CONSTRAINT `fk_tbl_user_project_tbl_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `survey`.`tbl_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_user_project_tbl_project1`
    FOREIGN KEY (`project_id`)
    REFERENCES `survey`.`tbl_project` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_tbl_user_project_tbl_user1_idx` ON `survey`.`tbl_user_project` (`user_id` ASC);

CREATE INDEX `fk_tbl_user_project_tbl_project1_idx` ON `survey`.`tbl_user_project` (`project_id` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
